changeLogFile=./changelog-master.xml
url=jdbc:sqlserver://localhost;databaseName=ConferenceManagamentDb;encrypt=true;trustServerCertificate=true
username=
password=!
driver=com.microsoft.sqlserver.jdbc.SQLServerDriver
classpath=mssql-jdbc-12.10.1.jre11.jar